[package]
name = "davidn5-mja8-projekt"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
ggez = "0.9.3"
rand = "0.9.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
